# Generated by Django 5.2.7 on 2025-12-12 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_academicperiod_options_alter_career_options_and_more'),
        ('users', '0002_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQualifiedCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Certifications, specialization notes, etc.')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.career')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_careers', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Qualified Career',
                'verbose_name_plural': 'Teacher Qualified Careers',
                'db_table': 'teacher_qualified_careers',
                'unique_together': {('teacher', 'career')},
            },
        ),
        migrations.CreateModel(
            name='TeacherQualifiedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Certifications, specialization notes, etc.')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_subjects', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Qualified Subject',
                'verbose_name_plural': 'Teacher Qualified Subjects',
                'db_table': 'teacher_qualified_subjects',
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
