# Generated by Django 5.2.7 on 2025-12-07 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_skip', models.BooleanField(default=False)),
                ('show_in_progress_bar', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Phase',
                'verbose_name_plural': 'Form Phases',
                'db_table': 'form_phases',
                'ordering': ['form_template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text_short', 'Short Text'), ('text_long', 'Long Text (Textarea)'), ('email', 'Email'), ('phone', 'Phone Number'), ('number', 'Number'), ('date_picker', 'Date Picker'), ('single_choice', 'Single Choice (Radio)'), ('multiple_choice', 'Multiple Choice (Checkbox)'), ('dropdown', 'Dropdown Select'), ('autocomplete', 'Autocomplete'), ('checkbox', 'Single Checkbox'), ('file_upload', 'File Upload'), ('course_selector', 'Course Selector'), ('schedule_viewer', 'Schedule Viewer'), ('accordion_section', 'Accordion Section'), ('divider', 'Divider'), ('info_text', 'Information Text'), ('payment_module', 'Payment Module')], max_length=30)),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(max_length=300)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='JSON object with validation rules. Examples:\n        - {"min_length": 5, "max_length": 100}\n        - {"pattern": "^[A-Z0-9]+$", "pattern_message": "Only uppercase letters and numbers"}\n        - {"min": 0, "max": 100}\n        - {"allowed_extensions": ["pdf", "jpg", "png"], "max_size_mb": 5}\n        - {"min_date": "2024-01-01", "max_date": "2024-12-31"}\n        ')),
                ('options', models.JSONField(blank=True, default=list, help_text='JSON array for choice fields. Examples:\n        - [{"value": "opt1", "label": "Option 1"}, {"value": "opt2", "label": "Option 2"}]\n        - For course_selector: fetched dynamically from API\n        ')),
                ('conditional_logic', models.JSONField(blank=True, default=dict, help_text='JSON object for conditional display. Example:\n        {"show_if": {"field_id": 123, "operator": "equals", "value": "yes"}}\n        {"show_if": {"field_id": 124, "operator": "contains", "value": ["option1", "option2"]}}\n        ')),
                ('max_selections', models.IntegerField(blank=True, help_text='For multiple_choice fields - limit number of selections', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('allowed_file_types', models.JSONField(blank=True, default=list, help_text="Array of allowed file extensions, e.g., ['pdf', 'jpg', 'png']")),
                ('max_file_size_mb', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('filter_by_career', models.BooleanField(default=False)),
                ('check_prerequisites', models.BooleanField(default=True)),
                ('check_schedule_conflicts', models.BooleanField(default=True)),
                ('max_credits', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.formphase')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'db_table': 'form_fields',
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, help_text='Email for non-authenticated users', max_length=254, null=True)),
                ('current_phase', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submission_data', models.JSONField(default=dict, help_text='JSON object storing all form field values:\n        {\n            "phase_1": {"field_1": "value", "field_2": "value"},\n            "phase_2": {"field_3": "value"},\n            ...\n        }\n        ')),
                ('uploaded_files', models.JSONField(blank=True, default=dict, help_text='JSON object mapping field IDs to file paths')),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='not_required', max_length=20)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'db_table': 'form_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='form_submissions/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='forms.formfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='forms.formsubmission')),
            ],
            options={
                'verbose_name': 'Form Submission File',
                'verbose_name_plural': 'Form Submission Files',
                'db_table': 'form_submission_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requires_authentication', models.BooleanField(default=False)),
                ('requires_payment', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Base payment amount in currency', max_digits=10, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('send_confirmation_email', models.BooleanField(default=True)),
                ('notification_emails', models.JSONField(blank=True, default=list, help_text='List of email addresses to notify on submission')),
                ('allow_drafts', models.BooleanField(default=True)),
                ('draft_expiration_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_submissions_per_user', models.IntegerField(blank=True, help_text='Leave blank for unlimited submissions', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Template',
                'verbose_name_plural': 'Form Templates',
                'db_table': 'form_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.formtemplate'),
        ),
        migrations.AddField(
            model_name='formphase',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='forms.formtemplate'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['phase', 'order'], name='form_fields_phase_i_47e702_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('phase', 'order')},
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['url_slug'], name='form_templa_url_slu_321450_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['is_active'], name='form_templa_is_acti_c9a9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form_template', 'status'], name='form_submis_form_te_ab4f20_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['user', 'status'], name='form_submis_user_id_3697fd_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['status', 'payment_status'], name='form_submis_status_91d31f_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['created_at'], name='form_submis_created_8c9d31_idx'),
        ),
        migrations.AddIndex(
            model_name='formphase',
            index=models.Index(fields=['form_template', 'order'], name='form_phases_form_te_1d46a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formphase',
            unique_together={('form_template', 'order')},
        ),
    ]
