# Generated by Django 5.2.7 on 2025-12-10 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0003_alter_careerenrollment_options_and_more'),
        ('users', '0002_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('exam', 'Examen'), ('assignment', 'Trabajo'), ('practical', 'Práctica'), ('project', 'Proyecto'), ('quiz', 'Quiz'), ('participation', 'Participación'), ('other', 'Otro')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Evaluation weight in percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_score', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('evaluation_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_legacy', to='enrollment.subjectgroup')),
            ],
            options={
                'verbose_name': 'Evaluation (Legacy)',
                'verbose_name_plural': 'Evaluations (Legacy)',
                'db_table': 'evaluations_legacy',
                'ordering': ['subject_group', '-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('passed', 'Aprobado'), ('failed', 'Reprobado'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('calculation_details', models.JSONField(blank=True, default=dict, help_text='Detalles del cálculo de la calificación final')),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to='enrollment.subjectenrollment')),
            ],
            options={
                'verbose_name': 'Final Grade',
                'verbose_name_plural': 'Final Grades',
                'db_table': 'final_grades',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalGradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_provisional_grades', models.BooleanField(default=False, help_text='Mostrar calificaciones provisionales a estudiantes')),
                ('is_published', models.BooleanField(default=False, help_text='Calificaciones finales publicadas')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('passing_score', models.DecimalField(decimal_places=2, default=5.0, help_text='Calificación mínima para aprobar', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rounding_method', models.CharField(choices=[('none', 'Sin redondeo'), ('up', 'Redondear hacia arriba'), ('down', 'Redondear hacia abajo'), ('nearest', 'Redondear al más cercano')], default='nearest', max_length=20)),
                ('decimal_places', models.IntegerField(default=2, help_text='Número de decimales en calificación final', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade_config', to='enrollment.subjectgroup')),
            ],
            options={
                'verbose_name': 'Final Grade Configuration',
                'verbose_name_plural': 'Final Grade Configurations',
                'db_table': 'final_grade_configs',
            },
        ),
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='users.teacher')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_reports', to='enrollment.subjectgroup')),
            ],
            options={
                'verbose_name': 'Grade Report',
                'verbose_name_plural': 'Grade Reports',
                'db_table': 'grade_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='GradingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría (ej: Exámenes, Trabajos, Quizzes)', max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Peso en porcentaje (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_categories', to='enrollment.subjectgroup')),
            ],
            options={
                'verbose_name': 'Grading Category',
                'verbose_name_plural': 'Grading Categories',
                'db_table': 'grading_categories',
                'ordering': ['subject_group', 'order', 'name'],
                'unique_together': {('subject_group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('task', 'Tarea'), ('quiz', 'Quiz'), ('exam', 'Examen'), ('project', 'Proyecto'), ('practical', 'Práctica'), ('participation', 'Participación'), ('other', 'Otro')], default='task', max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField(blank=True, help_text='Fecha de inicio (opcional)', null=True)),
                ('due_date', models.DateTimeField(help_text='Fecha límite de entrega')),
                ('published_at', models.DateTimeField(blank=True, help_text='Fecha de publicación', null=True)),
                ('scope', models.CharField(choices=[('all', 'Todos los estudiantes'), ('selected', 'Estudiantes seleccionados')], default='all', max_length=20)),
                ('allow_late_submission', models.BooleanField(default=True)),
                ('late_penalty_percent', models.DecimalField(decimal_places=2, default=0, help_text='Penalización por entrega tardía (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attachment', models.FileField(blank=True, help_text='Archivo adjunto del profesor (opcional)', null=True, upload_to='assignments/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_students', models.ManyToManyField(blank=True, help_text="Estudiantes asignados (si scope='selected')", related_name='assigned_tasks', to='users.student')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to='users.teacher')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='enrollment.subjectgroup')),
                ('category', models.ForeignKey(blank=True, help_text='Categoría de ponderación (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='grades.gradingcategory')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments',
                'ordering': ['subject_group', '-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, help_text='Respuesta en texto (opcional)', null=True)),
                ('submission_file', models.FileField(blank=True, help_text='Archivo de entrega del estudiante', null=True, upload_to='submissions/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Entregado'), ('late', 'Entrega tardía'), ('graded', 'Calificado'), ('returned', 'Devuelto')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de entrega', null=True)),
                ('is_late', models.BooleanField(default=False, help_text='Indica si la entrega fue tardía')),
                ('late_days', models.IntegerField(default=0, help_text='Días de retraso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='grades.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.student')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('feedback_file', models.FileField(blank=True, help_text='Archivo de retroalimentación (opcional)', null=True, upload_to='feedback/%Y/%m/%d/')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.assignment')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignments', to='users.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='grades.submission')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['subject_group', 'published_at'], name='assignments_subject_0061d7_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assignment_type'], name='assignments_assignm_6daa15_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignments_due_dat_708d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'student'], name='submissions_assignm_5339e3_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_dcc854_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['assignment', 'student'], name='grades_assignm_d1d1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student'], name='grades_student_b8b331_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('assignment', 'student')},
        ),
    ]
