# Generated by Django 5.2.7 on 2025-12-10 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_alter_careerenrollment_options_and_more'),
        ('grades', '0001_initial'),
        ('users', '0002_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='course_materials/%Y/%m/%d/')),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('folder', models.CharField(blank=True, help_text='Folder name for organization', max_length=100, null=True)),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=True, help_text='Whether the material is visible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='enrollment.subjectgroup')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Course Material',
                'verbose_name_plural': 'Course Materials',
                'db_table': 'course_materials',
                'ordering': ['subject_group', 'folder', 'order', 'title'],
            },
        ),
    ]
