# Generated by Django 5.2.7 on 2025-12-11 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_alter_careerenrollment_options_and_more'),
        ('grades', '0002_coursematerial'),
        ('users', '0002_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('true_false', 'Verdadero/Falso'), ('short_answer', 'Respuesta Corta'), ('essay', 'Ensayo')], max_length=20)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Explicación que se muestra después de responder')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order', models.IntegerField(default=1)),
                ('correct_answer', models.TextField(blank=True, help_text='Respuesta correcta para preguntas de respuesta corta')),
                ('case_sensitive', models.BooleanField(default=False, help_text='Distinguir mayúsculas/minúsculas en respuestas cortas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='grades.question')),
            ],
            options={
                'verbose_name': 'Opción de Pregunta',
                'verbose_name_plural': 'Opciones de Pregunta',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quiz_type', models.CharField(choices=[('practice', 'Práctica'), ('quiz', 'Quiz'), ('exam', 'Examen')], default='quiz', max_length=20)),
                ('time_limit', models.IntegerField(blank=True, help_text='Límite de tiempo en minutos (dejar en blanco para sin límite)', null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(default=1, help_text='Número máximo de intentos permitidos')),
                ('total_points', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('passing_score', models.DecimalField(decimal_places=2, default=70.0, help_text='Puntaje mínimo para aprobar (%)', max_digits=5)),
                ('randomize_questions', models.BooleanField(default=False, help_text='Randomizar el orden de las preguntas')),
                ('randomize_options', models.BooleanField(default=False, help_text='Randomizar el orden de las opciones')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Mostrar respuestas correctas después de completar')),
                ('show_feedback', models.BooleanField(default=True, help_text='Mostrar retroalimentación después de completar')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to='users.teacher')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='enrollment.subjectgroup')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='grades.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'En Progreso'), ('submitted', 'Enviado'), ('graded', 'Calificado')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje obtenido', max_digits=5, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje máximo posible', max_digits=5, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje obtenido', max_digits=5, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quiz_attempts', to='users.teacher')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='grades.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='users.student')),
            ],
            options={
                'verbose_name': 'Intento de Quiz',
                'verbose_name_plural': 'Intentos de Quiz',
                'ordering': ['-started_at'],
                'unique_together': {('quiz', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='grades.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='grades.questionoption')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='grades.quizattempt')),
            ],
            options={
                'verbose_name': 'Respuesta de Quiz',
                'verbose_name_plural': 'Respuestas de Quiz',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
