# Generated by Django 5.2.7 on 2025-11-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'Academic Period', 'verbose_name_plural': 'Academic Periods'},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['name'], 'verbose_name': 'Career', 'verbose_name_plural': 'Careers'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['building', 'floor', 'code'], 'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={'ordering': ['-start_year'], 'verbose_name': 'Study Plan', 'verbose_name_plural': 'Study Plans'},
        ),
        migrations.AlterModelOptions(
            name='studyplansubject',
            options={'verbose_name': 'Study Plan Subject', 'verbose_name_plural': 'Study Plan Subjects'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['course_year', 'semester', 'name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
