# Generated by Django 5.2.7 on 2025-10-07 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enrolled', 'Inscrito'), ('dropped', 'Retirado'), ('completed', 'Completado'), ('failed', 'Reprobado')], default='enrolled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inscripción a Asignatura',
                'verbose_name_plural': 'Inscripciones a Asignaturas',
                'db_table': 'subject_enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('max_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_enrollment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo de Asignatura',
                'verbose_name_plural': 'Grupos de Asignatura',
                'db_table': 'subject_groups',
                'ordering': ['subject', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('waiting', 'En Espera'), ('enrolled', 'Inscrito'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
                'db_table': 'waiting_lists',
                'ordering': ['subject_group', 'position'],
            },
        ),
        migrations.CreateModel(
            name='CareerEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('dropped', 'Abandonado'), ('suspended', 'Suspendido')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.career')),
            ],
            options={
                'verbose_name': 'Matriculación de Carrera',
                'verbose_name_plural': 'Matriculaciones de Carrera',
                'db_table': 'career_enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
