# Generated by Django 5.2.7 on 2025-10-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('enrollment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_enrollments', to='users.student'),
        ),
        migrations.AddField(
            model_name='careerenrollment',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.studyplan'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='career_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='enrollment.careerenrollment'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='users.student'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='academic.academicperiod'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='subject_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enrollment.subjectgroup'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_lists', to='users.student'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='subject_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='enrollment.subjectgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='careerenrollment',
            unique_together={('student', 'career', 'study_plan')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectgroup',
            unique_together={('subject', 'academic_period', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectenrollment',
            unique_together={('student', 'subject_group')},
        ),
        migrations.AlterUniqueTogether(
            name='waitinglist',
            unique_together={('student', 'subject_group')},
        ),
    ]
