# Generated by Django 5.2.7 on 2025-11-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerenrollment',
            options={'ordering': ['-enrollment_date'], 'verbose_name': 'Career Enrollment', 'verbose_name_plural': 'Career Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='subjectenrollment',
            options={'ordering': ['-enrollment_date'], 'verbose_name': 'Subject Enrollment', 'verbose_name_plural': 'Subject Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='subjectgroup',
            options={'ordering': ['subject', 'code'], 'verbose_name': 'Subject Group', 'verbose_name_plural': 'Subject Groups'},
        ),
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'ordering': ['subject_group', 'position'], 'verbose_name': 'Waiting List', 'verbose_name_plural': 'Waiting Lists'},
        ),
    ]
