# Generated by Django 5.2.7 on 2025-11-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['time_slot__day_of_week', 'time_slot__start_time'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'ordering': ['-assignment_date'], 'verbose_name': 'Teacher Assignment', 'verbose_name_plural': 'Teacher Assignments'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
    ]
