# Generated by Django 5.2.7 on 2025-12-09 08:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_academicperiod_options_alter_career_options_and_more'),
        ('enrollment', '0003_alter_careerenrollment_options_and_more'),
        ('schedules', '0003_alter_schedule_options_and_more'),
        ('users', '0002_alter_student_options_alter_teacher_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('teacher', 'Profesor'), ('tutor', 'Tutor de Aula'), ('department_head', 'Jefe de Departamento'), ('head_of_studies', 'Jefe de Estudios'), ('deputy_director', 'Subdirector'), ('director', 'Director')], max_length=50, unique=True)),
                ('required_free_hours_per_week', models.IntegerField(help_text='Horas no lectivas requeridas por semana', validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.IntegerField(default=1, help_text='Mayor número = mayor prioridad en asignación', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='briefcase', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher Role',
                'verbose_name_plural': 'Teacher Roles',
                'db_table': 'teacher_roles',
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='weekly_hours',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='academic.academicperiod'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='duration_minutes',
            field=models.IntegerField(default=60, editable=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('academic_period', 'day_of_week', 'start_time')},
        ),
        migrations.CreateModel(
            name='ScheduleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('backtracking', 'Backtracking con Forward Checking'), ('genetic', 'Algoritmo Genético'), ('simulated_annealing', 'Recocido Simulado')], default='backtracking', max_length=50)),
                ('max_execution_time_seconds', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(30)])),
                ('optimization_priority', models.CharField(choices=[('teachers', 'Priorizar profesores'), ('students', 'Priorizar estudiantes'), ('classrooms', 'Priorizar aulas'), ('balanced', 'Balanceado')], default='balanced', max_length=20)),
                ('allow_teacher_gaps', models.BooleanField(default=True, help_text='Permitir huecos entre clases de profesores')),
                ('max_daily_hours_per_teacher', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_daily_hours_per_group', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_break_between_classes', models.IntegerField(default=0, help_text='Minutos mínimos de descanso entre clases', validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_minimize_teacher_gaps', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weight_teacher_preferences', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weight_balanced_distribution', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weight_classroom_proximity', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weight_minimize_daily_changes', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_configuration', to='academic.academicperiod')),
            ],
            options={
                'verbose_name': 'Schedule Configuration',
                'verbose_name_plural': 'Schedule Configurations',
                'db_table': 'schedule_configurations',
            },
        ),
        migrations.CreateModel(
            name='ScheduleGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('partial', 'Parcial')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_seconds', models.FloatField(blank=True, null=True)),
                ('total_sessions_to_schedule', models.IntegerField(default=0)),
                ('sessions_scheduled', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('conflicts_detected', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('optimization_score', models.FloatField(blank=True, null=True)),
                ('algorithm_used', models.CharField(blank=True, max_length=50)),
                ('algorithm_parameters', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_generations', to='academic.academicperiod')),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='schedules.scheduleconfiguration')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule Generation',
                'verbose_name_plural': 'Schedule Generations',
                'db_table': 'schedule_generations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hours_per_week', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('max_consecutive_hours', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('max_daily_hours', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('preferred_days', models.JSONField(blank=True, default=list, help_text='Lista de días preferidos [0-6] donde 0=Lunes')),
                ('preferred_start_time', models.TimeField(blank=True, null=True)),
                ('preferred_end_time', models.TimeField(blank=True, null=True)),
                ('color_code', models.CharField(default='#10B981', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_preferences', to='academic.academicperiod')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_preferences', to='users.teacher')),
                ('unavailable_time_slots', models.ManyToManyField(blank=True, help_text='Franjas horarias no disponibles', related_name='unavailable_for_teachers', to='schedules.timeslot')),
            ],
            options={
                'verbose_name': 'Teacher Preferences',
                'verbose_name_plural': 'Teacher Preferences',
                'db_table': 'teacher_preferences',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_slots', models.IntegerField(default=1, help_text='Número de franjas horarias consecutivas', validators=[django.core.validators.MinValueValidator(1)])),
                ('session_type', models.CharField(choices=[('lecture', 'Clase Teórica'), ('lab', 'Laboratorio'), ('workshop', 'Taller'), ('seminar', 'Seminario'), ('exam', 'Examen')], default='lecture', max_length=20)),
                ('is_locked', models.BooleanField(default=False, help_text='Si está bloqueado, no se puede modificar automáticamente')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='academic.classroom')),
                ('schedule_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schedules.schedulegeneration')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='enrollment.subjectgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='users.teacher')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='schedules.teacherassignment')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='schedules.timeslot')),
            ],
            options={
                'verbose_name': 'Schedule Session',
                'verbose_name_plural': 'Schedule Sessions',
                'db_table': 'schedule_sessions',
                'ordering': ['time_slot__day_of_week', 'time_slot__start_time'],
                'unique_together': {('schedule_generation', 'time_slot', 'classroom'), ('schedule_generation', 'time_slot', 'subject_group'), ('schedule_generation', 'time_slot', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='TeacherRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_free_hours', models.IntegerField(default=0, help_text='Horas adicionales no lectivas específicas para este profesor', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_role_assignments', to='academic.academicperiod')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schedules.teacherrole')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Role Assignment',
                'verbose_name_plural': 'Teacher Role Assignments',
                'db_table': 'teacher_role_assignments',
                'unique_together': {('teacher', 'role', 'academic_period')},
            },
        ),
    ]
