# Generated by Django 5.2.7 on 2025-12-09 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_academicperiod_options_alter_career_options_and_more'),
        ('schedules', '0004_teacherrole_teacherassignment_weekly_hours_and_more'),
        ('users', '0002_alter_student_options_alter_teacher_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_type', models.CharField(choices=[('full', 'Disponibilidad Completa'), ('restricted', 'Disponibilidad Restringida'), ('unavailable', 'No Disponible')], default='full', help_text='Tipo de disponibilidad del profesor', max_length=20)),
                ('max_teaching_hours', models.IntegerField(blank=True, help_text='Máximo de horas semanales que puede dar clase (null = sin límite)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('blocked_days', models.JSONField(blank=True, default=list, help_text='Lista de días bloqueados [0-6] donde 0=Lunes, no puede dar clase estos días')),
                ('restriction_reason', models.CharField(blank=True, help_text="Razón de la restricción (ej: 'De permiso', 'Medio tiempo', 'Proyecto especial')", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availability', to='academic.academicperiod')),
                ('available_time_slots', models.ManyToManyField(blank=True, help_text="Franjas horarias donde el profesor SÍ puede dar clase (solo si es 'restricted')", related_name='available_for_teachers', to='schedules.timeslot')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_availability', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_restrictions', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Availability',
                'verbose_name_plural': 'Teacher Availabilities',
                'db_table': 'teacher_availability',
                'ordering': ['teacher__user__last_name'],
                'unique_together': {('teacher', 'academic_period')},
            },
        ),
    ]
