# Generated by Django 5.2.7 on 2025-12-13 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_academicperiod_options_alter_career_options_and_more'),
        ('schedules', '0005_teacheravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegeneration',
            name='career',
            field=models.ForeignKey(blank=True, help_text='Carrera para la cual se generó este horario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_generations', to='academic.career'),
        ),
    ]
