# Generated by Django 5.2.7 on 2025-12-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_schedulegeneration_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegeneration',
            name='batch_id',
            field=models.UUIDField(blank=True, help_text='ID del lote de generación - agrupa múltiples generaciones creadas en la misma ejecución', null=True),
        ),
    ]
