# Generated by Django 5.2.7 on 2025-12-14 16:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_academicperiod_options_alter_career_options_and_more'),
        ('schedules', '0007_schedulegeneration_batch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfiguration',
            name='max_classes_per_day',
            field=models.IntegerField(default=8, help_text='Máximo número de clases permitidas por día para un grupo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.CreateModel(
            name='BlockedTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('global', 'Global - Todas las Carreras'), ('career', 'Por Carrera Específica'), ('classroom', 'Por Aula Específica')], default='global', help_text='Tipo de bloqueo: global, por carrera o por aula', max_length=20)),
                ('reason', models.CharField(help_text='Razón del bloqueo (ej: "Mantenimiento", "Evento especial", "Reunión general")', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(help_text='Período académico en el cual aplica el bloqueo', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_time_slots', to='academic.academicperiod')),
                ('career', models.ForeignKey(blank=True, help_text='Carrera afectada (solo si block_type es "career")', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_time_slots', to='academic.career')),
                ('classroom', models.ForeignKey(blank=True, help_text='Aula afectada (solo si block_type es "classroom")', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_time_slots', to='academic.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocked_time_slots', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(help_text='Franja horaria bloqueada', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='schedules.timeslot')),
            ],
            options={
                'verbose_name': 'Blocked Time Slot',
                'verbose_name_plural': 'Blocked Time Slots',
                'db_table': 'blocked_time_slots',
                'ordering': ['time_slot__day_of_week', 'time_slot__start_time'],
                'unique_together': {('academic_period', 'time_slot', 'block_type', 'career', 'classroom')},
            },
        ),
    ]
