# Generated by Django 5.2.7 on 2025-12-14 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_scheduleconfiguration_max_classes_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfiguration',
            name='max_sessions_per_subject_per_day',
            field=models.IntegerField(default=2, help_text='Máximo número de sesiones de la misma materia por día', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
